### ISSUE TITLE
适配go-cqhttp

### ISSUE THREAD

**Issue by hanximeng** [littlegao233/PFBridge#1]
请问有go-cqhttp的适配计划吗

**Comment by LazuliKao** [comment]
待基本功能完善后会考虑

**Comment by LazuliKao** [comment]
如果有现成的go-cqhttpAPI的C#封装可留下链接

**Comment by LazuliKao** [comment]
已找到，之后会通过该封装来适配go-cqhttp，https://github.com/Yukari316/Sora
